[package]
name = "rtmp"
version = "0.1.0"
authors = ["Stargateur <antoine.plaskowski@epitech.eu>"]

[dependencies]
byteorder = "^0.5.3"
time = "^0.1"
rand = "^0.3"
amf = { git = "https://github.com/TwiceCast/amf.git" }
